# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54895cb70b9f665c8e0bdc645b8c4eeb52eda189811e77277a9bc092ab061ab18b745c18b017549a3380bc6f9149b10e4784bea11f1b642ceaeb0b20f9a7ada7

test:
  secret_key_base: 527978f5bb4b2b88eaf36fc30723d053d1136ddc5e4952e17111d03669b8c4bb57a2f30ca78079c68c128149b10d2b91974830091260e8140e8568eb0b3cee33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
